# Site settings
title:          Walker and Company Engineering Blog
description:    ""
baseurl:        "/"
url:            "eng.walkerandcompany.com"

# Author
author:
  name:         Walker and Company
  url:          walkerandcompany.com
  email:        mts@walkerandcompany.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
